development:
  adapter: async

test:
  adapter: test

production:
  # adapter: redis
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: mini_talk_app_production

# cable.ymlとはActionCableを使用する際の設定を記述するファイルです。
# ここでは、本番環境の仕様設定に編集を加えます。
# 具体的には、使用する adapter の指定を変更します。

# ActionCableは、サーバーから送信された情報をクライアントへ提供する仕組みがあって成り立っています。
# その仕組みと連携するためのものをadapterと言います。

